language: java
sudo: false

jobs:
  include:
    # Stage Test - Job 1-2:  Builds against all available Jdks.
    - stage: test
      jdk: openjdk7
      script: mvn -q install
    - jdk: oraclejdk8
      script: mvn -q install

branches:
  only:
  - master